// This file was generated by a program.
// Please do not edit this file directly.
package testpackage

import (
// package names to be imported
)

type AlarmStm3State uint8
const (
AlarmStm3Release AlarmStm3State = iota
AlarmStm3Push
)

var AlarmStm3Eod Eod
var AlarmStm3CurrentState AlarmStm3State
var AlarmStm3NextState AlarmStm3State

func init() {
AlarmStm3Initialize()
}

func AlarmStm3Initialize() {
AlarmStm3Eod = Entry
AlarmStm3CurrentState = AlarmStm3Release
AlarmStm3NextState = AlarmStm3Release
}

func AlarmStm3Task() {
switch AlarmStm3CurrentState {
case AlarmStm3Release:
if AlarmStm3Eod == Entry {
AlarmStm3ReleaseEntry()
AlarmStm3Eod = Do
}
if AlarmStm3Eod == Do {
AlarmStm3ReleaseDo()
if AlarmStm3ReleasePushCond() {
AlarmStm3ReleasePushAction()
AlarmStm3NextState = AlarmStm3Push
AlarmStm3Eod = Exit
}
}
if AlarmStm3Eod == Exit {
AlarmStm3ReleaseExit()
AlarmStm3Eod = Entry
}
case AlarmStm3Push:
if AlarmStm3Eod == Entry {
AlarmStm3PushEntry()
AlarmStm3Eod = Do
}
if AlarmStm3Eod == Do {
AlarmStm3PushDo()
}
if AlarmStm3Eod == Exit {
AlarmStm3PushExit()
AlarmStm3Eod = Entry
}
}
}

func AlarmStm3Update() {
switch AlarmStm3CurrentState {
case AlarmStm3Release:
case AlarmStm3Push:
}
AlarmStm3CurrentState = AlarmStm3NextState
}

