// This file was generated by a program.
package testpackage
import (
// package names to be imported
)
///////////////////////////////////////////////
// functions for State AlarmStm3Release
///////////////////////////////////////////////

func AlarmStm3ReleaseEntry() {
if debug {
logger.Println("Entering State AlarmStm3Release")
}
// Please write an enter process for State AlarmStm3Release
}

func AlarmStm3ReleaseDo() {
// Please write a do process for State AlarmStm3Release
}

func AlarmStm3ReleaseExit() {
if debug {
logger.Println("Leaving State AlarmStm3Release")
}
// Please write an exit process for State AlarmStm3Release
}

///////////////////////////////////////////////
// functions for State AlarmStm3Push
///////////////////////////////////////////////

func AlarmStm3PushEntry() {
if debug {
logger.Println("Entering State AlarmStm3Push")
}
// Please write an enter process for State AlarmStm3Push
}

func AlarmStm3PushDo() {
// Please write a do process for State AlarmStm3Push
}

func AlarmStm3PushExit() {
if debug {
logger.Println("Leaving State AlarmStm3Push")
}
// Please write an exit process for State AlarmStm3Push
}

///////////////////////////////////////////////
// Conditions
///////////////////////////////////////////////

func AlarmStm3ReleasePushCond() bool {
return button1 || button2 || button3
}

///////////////////////////////////////////////
// Actions
///////////////////////////////////////////////

func AlarmStm3ReleasePushAction() {
// Please edit the action when Push occurs at State Release
}

