// This file was generated by a program.
package testpackage

import (
// package names to be imported
)

type Eod uint8

const (
Entry Eod = iota
Do
Exit
)

type DebugLogger interface {
Println(...interface{})
}

var logger DebugLogger

func ConfigureLogger(d DebugLogger) {
logger = d
}

const (
debug = true
)

// func InputDevice() {
// Please edit to get status of input devices
// }

// func OutputDevice() {
// Please edit to put status of output devices
// }

