// This file was generated by a program.
package testpackage

import (
"log"
"testing"
"time"
 stm2go "github.com/JuliaMBD/stm2go/testing"
)

type TestLogger struct{}

func (l TestLogger) Println(s ...interface{}) {
log.Println(s...)
}

func TestExample(t *testing.T) {
ConfigureLogger(TestLogger{})

env := stm2go.NewTestEnv()

env.Add(stm2go.Continue, func() {
for {
// InputDevice()
EntryrootStm0Task()
// OutputDevice()
time.Sleep(10 * time.Millisecond)
}
})
env.Add(stm2go.Done, func() {
time.Sleep(100 * time.Millisecond) // 10 times runs
})
env.Set(1)
env.Go()
}
