// This file was generated by a program.
package testpackage
import (
// package names to be imported
)
///////////////////////////////////////////////
// functions for State TimerSetStm1MinPush
///////////////////////////////////////////////

func TimerSetStm1MinPushEntry() {
if debug {
logger.Println("Entering State TimerSetStm1MinPush")
}
increaseMin()
}

func TimerSetStm1MinPushDo() {
// Please write a do process for State TimerSetStm1MinPush
}

func TimerSetStm1MinPushExit() {
if debug {
logger.Println("Leaving State TimerSetStm1MinPush")
}
// Please write an exit process for State TimerSetStm1MinPush
}

///////////////////////////////////////////////
// functions for State TimerSetStm1SecPush
///////////////////////////////////////////////

func TimerSetStm1SecPushEntry() {
if debug {
logger.Println("Entering State TimerSetStm1SecPush")
}
increaseSec()
}

func TimerSetStm1SecPushDo() {
// Please write a do process for State TimerSetStm1SecPush
}

func TimerSetStm1SecPushExit() {
if debug {
logger.Println("Leaving State TimerSetStm1SecPush")
}
// Please write an exit process for State TimerSetStm1SecPush
}

///////////////////////////////////////////////
// functions for State TimerSetStm1Release
///////////////////////////////////////////////

func TimerSetStm1ReleaseEntry() {
if debug {
logger.Println("Entering State TimerSetStm1Release")
}
// Please write an enter process for State TimerSetStm1Release
}

func TimerSetStm1ReleaseDo() {
// Please write a do process for State TimerSetStm1Release
}

func TimerSetStm1ReleaseExit() {
if debug {
logger.Println("Leaving State TimerSetStm1Release")
}
// Please write an exit process for State TimerSetStm1Release
}

///////////////////////////////////////////////
// functions for State TimerSetStm1StartPush
///////////////////////////////////////////////

func TimerSetStm1StartPushEntry() {
if debug {
logger.Println("Entering State TimerSetStm1StartPush")
}
// Please write an enter process for State TimerSetStm1StartPush
}

func TimerSetStm1StartPushDo() {
// Please write a do process for State TimerSetStm1StartPush
}

func TimerSetStm1StartPushExit() {
if debug {
logger.Println("Leaving State TimerSetStm1StartPush")
}
// Please write an exit process for State TimerSetStm1StartPush
}

///////////////////////////////////////////////
// Conditions
///////////////////////////////////////////////

func TimerSetStm1MinPushReleaseCond() bool {
return !button1
}

func TimerSetStm1SecPushReleaseCond() bool {
return !button2
}

func TimerSetStm1ReleaseStartCond() bool {
return (min != 0 || sec != 0) && button3
}

func TimerSetStm1ReleasePush2Cond() bool {
return button2
}

func TimerSetStm1ReleasePush1Cond() bool {
return button1
}

///////////////////////////////////////////////
// Actions
///////////////////////////////////////////////

func TimerSetStm1MinPushReleaseAction() {
// Please edit the action when Release occurs at State MinPush
}

func TimerSetStm1SecPushReleaseAction() {
// Please edit the action when Release occurs at State SecPush
}

func TimerSetStm1ReleaseStartAction() {
// Please edit the action when Start occurs at State Release
}

func TimerSetStm1ReleasePush2Action() {
// Please edit the action when Push2 occurs at State Release
}

func TimerSetStm1ReleasePush1Action() {
// Please edit the action when Push1 occurs at State Release
}

