// This file was generated by a program.
package testpackage
import (
// package names to be imported
)
///////////////////////////////////////////////
// functions for State TimerStartStm2Count
///////////////////////////////////////////////

func TimerStartStm2CountEntry() {
if debug {
logger.Println("Entering State TimerStartStm2Count")
}
count = 0
}

func TimerStartStm2CountDo() {
count += 1
}

func TimerStartStm2CountExit() {
if debug {
logger.Println("Leaving State TimerStartStm2Count")
}
// Please write an exit process for State TimerStartStm2Count
}

///////////////////////////////////////////////
// functions for State TimerStartStm2StopPush
///////////////////////////////////////////////

func TimerStartStm2StopPushEntry() {
if debug {
logger.Println("Entering State TimerStartStm2StopPush")
}
// Please write an enter process for State TimerStartStm2StopPush
}

func TimerStartStm2StopPushDo() {
// Please write a do process for State TimerStartStm2StopPush
}

func TimerStartStm2StopPushExit() {
if debug {
logger.Println("Leaving State TimerStartStm2StopPush")
}
// Please write an exit process for State TimerStartStm2StopPush
}

///////////////////////////////////////////////
// Conditions
///////////////////////////////////////////////

func TimerStartStm2CountOneSecCond() bool {
return count == Sec1
}

func TimerStartStm2CountPushCond() bool {
return button3
}

///////////////////////////////////////////////
// Actions
///////////////////////////////////////////////

func TimerStartStm2CountOneSecAction() {
decreaseSec()
}

func TimerStartStm2CountPushAction() {
// Please edit the action when Push occurs at State Count
}

