// This file was generated by a program.
// Please do not edit this file directly.
package testpackage

import (
// package names to be imported
)

type TimerSetStm1State uint8
const (
TimerSetStm1Release TimerSetStm1State = iota
TimerSetStm1StartPush
TimerSetStm1MinPush
TimerSetStm1SecPush
)

var TimerSetStm1Eod Eod
var TimerSetStm1CurrentState TimerSetStm1State
var TimerSetStm1NextState TimerSetStm1State

func init() {
TimerSetStm1Initialize()
}

func TimerSetStm1Initialize() {
TimerSetStm1Eod = Entry
TimerSetStm1CurrentState = TimerSetStm1Release
TimerSetStm1NextState = TimerSetStm1Release
}

func TimerSetStm1Task() {
switch TimerSetStm1CurrentState {
case TimerSetStm1Release:
if TimerSetStm1Eod == Entry {
TimerSetStm1ReleaseEntry()
TimerSetStm1Eod = Do
}
if TimerSetStm1Eod == Do {
TimerSetStm1ReleaseDo()
if TimerSetStm1ReleaseStartCond() {
TimerSetStm1ReleaseStartAction()
TimerSetStm1NextState = TimerSetStm1StartPush
TimerSetStm1Eod = Exit
}
if TimerSetStm1ReleasePush2Cond() {
TimerSetStm1ReleasePush2Action()
TimerSetStm1NextState = TimerSetStm1SecPush
TimerSetStm1Eod = Exit
}
if TimerSetStm1ReleasePush1Cond() {
TimerSetStm1ReleasePush1Action()
TimerSetStm1NextState = TimerSetStm1MinPush
TimerSetStm1Eod = Exit
}
}
if TimerSetStm1Eod == Exit {
TimerSetStm1ReleaseExit()
TimerSetStm1Eod = Entry
}
case TimerSetStm1StartPush:
if TimerSetStm1Eod == Entry {
TimerSetStm1StartPushEntry()
TimerSetStm1Eod = Do
}
if TimerSetStm1Eod == Do {
TimerSetStm1StartPushDo()
}
if TimerSetStm1Eod == Exit {
TimerSetStm1StartPushExit()
TimerSetStm1Eod = Entry
}
case TimerSetStm1MinPush:
if TimerSetStm1Eod == Entry {
TimerSetStm1MinPushEntry()
TimerSetStm1Eod = Do
}
if TimerSetStm1Eod == Do {
TimerSetStm1MinPushDo()
if TimerSetStm1MinPushReleaseCond() {
TimerSetStm1MinPushReleaseAction()
TimerSetStm1NextState = TimerSetStm1Release
TimerSetStm1Eod = Exit
}
}
if TimerSetStm1Eod == Exit {
TimerSetStm1MinPushExit()
TimerSetStm1Eod = Entry
}
case TimerSetStm1SecPush:
if TimerSetStm1Eod == Entry {
TimerSetStm1SecPushEntry()
TimerSetStm1Eod = Do
}
if TimerSetStm1Eod == Do {
TimerSetStm1SecPushDo()
if TimerSetStm1SecPushReleaseCond() {
TimerSetStm1SecPushReleaseAction()
TimerSetStm1NextState = TimerSetStm1Release
TimerSetStm1Eod = Exit
}
}
if TimerSetStm1Eod == Exit {
TimerSetStm1SecPushExit()
TimerSetStm1Eod = Entry
}
}
}

func TimerSetStm1Update() {
switch TimerSetStm1CurrentState {
case TimerSetStm1SecPush:
case TimerSetStm1Release:
case TimerSetStm1StartPush:
case TimerSetStm1MinPush:
}
TimerSetStm1CurrentState = TimerSetStm1NextState
}

